Fixed one failing test for old starlette version
This is what it gave in this test:
> RuntimeError: There is no current event loop in thread 'MainThread'.

I am using vanilla Starlette test client and probably it does not know
how to get an asyncio loop properly.
It's no problem: only fails in unit tests