Added a fix for JWT token
This test fails on JWToken because it has the following field:

> SECRET_KEY: ClassVar[str]

There's a bug in Python that fails on ClassVar`s in type annotations
and says the following:

> TypeError: typing.ClassVar[str] is not valid as type argument

We disable this test for these specific versions